---
name: Build Documentation

on:
  workflow_call:

jobs:
  Docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Python 3.10 For Nox
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: "3.10"

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install "nox==$NOX_VERSION" "uv==$UV_VERSION"
        env:
          NOX_VERSION: '2025.5.1'
          UV_VERSION: '0.8.18'

      - name: Install Doc Requirements
        run: |
          nox --force-color -e docs --install-only

      - name: Build Docs
        env:
          SKIP_REQUIREMENTS_INSTALL: true
        run: |
          nox --force-color -e docs

      - name: Upload built docs as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: html-docs
          path: docs/_build/html

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: exitstatus-${{ github.job }}
          path: exitstatus
          if-no-files-found: error
