---
name: Build Documentation

on:
  workflow_call:

jobs:
  Docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Python 3.10 For Nox
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: "3.10"

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Install Doc Requirements
        run: |
          nox --force-color -e docs --install-only

      - name: Build Docs
        env:
          SKIP_REQUIREMENTS_INSTALL: true
        run: |
          nox --force-color -e docs

      - name: Upload built docs as artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        with:
          name: html-docs
          path: docs/_build/html

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        with:
          name: exitstatus-${{ github.job }}
          path: exitstatus
          if-no-files-found: error
