---
name: Salt Extension Python Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Build Python Packages (wheel and sdist)
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
        with:
          python-version: "3.10"

      - name: Install build tools
        run: >-
          python -m
          pip install
          build
          setuptools_scm
          --user

      - name: Echo Version
        run: echo "${{ inputs.version }}"

      - name: Build Wheel
        run: python -m build --outdir dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        if: always()
        with:
          name: salt-extension-${{ inputs.version }}-packages
          path: dist/*
          retention-days: 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: exitstatus-${{ github.job }}
          path: exitstatus
          if-no-files-found: error
