---
name: Salt Extension Python Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Build Python Packages (wheel and sdist)
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: "3.10"

      - name: Install build tools
        run: >-
          python -m
          pip install
          build
          setuptools_scm
          --user

      - name: Echo Version
        run: echo "${{ inputs.version }}"

      - name: Build Wheel
        run: python -m build --outdir dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        if: always()
        with:
          name: salt-extension-${{ inputs.version }}-packages
          path: dist/*
          retention-days: 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        with:
          name: exitstatus-${{ github.job }}
          path: exitstatus
          if-no-files-found: error
